### ISSUE TITLE
"Configure Win2PDF Auto-name" should not give the OCR PDF file type as an option unless the Win2PDF Desktop w/OCR is installed

### ISSUE THREAD

**Issue by slebakken** [win2pdf/Win2PDF.Samples#11]
In 10.0.85, the "Configure Auto-name" includes a drop down to change/set the filetype so you don't have to break out of Auto-name to change the file type.  One use case for this is changing to OCR PDF file type for content/search field based file naming.

I had a customer that installed 10.0.85, thought they could set the file type to OCR but they had not yet downloaded the Win2PDF Desktop w/OCR setup program.  (https://helpdesk.win2pdf.com/index.php?/Knowledgebase/Article/View/197/15/win2pdf-desktop-with-ocr-download)

It would be less confusing if it could check to make sure they have the OCR libraries installed before giving that as an option.

**Comment by lebakken** [comment]
fixed.
